-- MySQL Script generated by MySQL Workbench
-- Tue Dec  9 19:24:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Senha_usuario` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `CPF_Usuario` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(15) NULL,
  `  created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `CPF_Usuario_UNIQUE` (`CPF_Usuario` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denúncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Denúncias` (
  `idDenúncias` INT NOT NULL,
  `Manguezal_Id` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  `Titulo` VARCHAR(200) NOT NULL,
  `Descrição` TEXT NOT NULL,
  `Tipo_Reclamação` ENUM('poluicao', 'desmatamento', 'pesca_ilegal', 'outros') NOT NULL,
  `Status` ENUM('pendente', 'em_analise', 'resolvido', 'arquivado') NOT NULL DEFAULT 'pendente',
  `Latitude` DECIMAL(10,8) NULL,
  `Longitude` DECIMAL(11,8) NULL,
  `Fotos` JSON NULL,
  `Mangues_id_mangues` INT NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`idDenúncias`, `Mangues_id_mangues`, `Usuarios_id_usuario`),
  INDEX `fk_Denúncias_Mangues1_idx` (`Mangues_id_mangues` ASC) VISIBLE,
  INDEX `fk_Denúncias_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Denúncias_Mangues1`
    FOREIGN KEY (`Mangues_id_mangues`)
    REFERENCES `mydb`.`Mangues` (`id_mangues`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Denúncias_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `mydb`.`Usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mangues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mangues` (
  `id_mangues` INT NOT NULL,
  `Nome_Mangues` VARCHAR(100) NOT NULL,
  `Localização` POINT NOT NULL,
  `Estado` VARCHAR(50) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Descrição` TEXT NULL,
  PRIMARY KEY (`id_mangues`),
  CONSTRAINT `(remetente_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `(destinatario_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `(denuncia_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Denúncias` ()
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temperatura` (
  `idTemperatura_Manguezal` INT NOT NULL AUTO_INCREMENT,
  `Temperatura_Registro` DECIMAL(4,2) NOT NULL,
  `data_registro` DATETIME NOT NULL,
  `Notes` TEXT NULL,
  `mangue_id` INT NULL,
  PRIMARY KEY (`idTemperatura_Manguezal`),
  CONSTRAINT `(usuario_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ` (mangue_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Mangues` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensagens` (
  `idMensagens` INT NOT NULL,
  `Rementent_Id` INT NOT NULL,
  `Destinatario_Id` INT NOT NULL,
  `Subjetivo` VARCHAR(200) NOT NULL,
  `Conteudo` TEXT NOT NULL,
  `Reclamação_Id` INT NOT NULL,
  `Mangues_id_mangues` INT NOT NULL,
  PRIMARY KEY (`idMensagens`, `Mangues_id_mangues`),
  INDEX `fk_Mensagens_Mangues1_idx` (`Mangues_id_mangues` ASC) VISIBLE,
  CONSTRAINT `fk_Mensagens_Mangues1`
    FOREIGN KEY (`Mangues_id_mangues`)
    REFERENCES `mydb`.`Mangues` (`id_mangues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resposta_Denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resposta_Denuncia` (
  `idResposta_Denuncia` INT NULL AUTO_INCREMENT,
  `denuncia_id` INT NOT NULL,
  `usuario_id` VARCHAR(45) NOT NULL,
  `resposta` TEXT NOT NULL,
  `acao_tomada` VARCHAR(200) NULL,
  `status_update` ENUM('em_analise', 'resolvido', 'arquivado') NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idResposta_Denuncia`),
  CONSTRAINT `(denuncia_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Denúncias` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `(usuario_id)`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
