-- MySQL Script generated by MySQL Workbench
-- Tue Dec  9 19:44:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Local` VARCHAR(100) NOT NULL,
  `CPF_Gerente` CHAR(11) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `CPF_Empregado` VARCHAR(15) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  `CEP` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`CPF_Empregado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empregado` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Sexo` ENUM('M', 'F') NOT NULL,
  `Salario` DECIMAL(10,2) NOT NULL,
  `idDepartamento` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Endereço_CPF_Empregado` VARCHAR(15) NOT NULL,
  `Departamento_idDepartamento1` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Empregado_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  INDEX `fk_Empregado_Endereço1_idx` (`Endereço_CPF_Empregado` ASC) VISIBLE,
  INDEX `fk_Empregado_Departamento2_idx` (`Departamento_idDepartamento1` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empregado_Endereço1`
    FOREIGN KEY (`Endereço_CPF_Empregado`)
    REFERENCES `mydb`.`Endereço` (`CPF_Empregado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empregado_Departamento2`
    FOREIGN KEY (`Departamento_idDepartamento1`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `idDependente` INT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `DataNasc` DATE NULL,
  `Parentesco` VARCHAR(30) NULL,
  `CPF_Empregado` CHAR(11) NULL,
  `Empregado_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`idDependente`),
  INDEX `fk_Dependente_Empregado1_idx` (`Empregado_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Dependente_Empregado1`
    FOREIGN KEY (`Empregado_CPF`)
    REFERENCES `mydb`.`Empregado` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BombComb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BombComb` (
  `idBomba` INT NULL AUTO_INCREMENT,
  `DataAbastecimento` DATE NOT NULL,
  `IdVenda` INT NULL,
  PRIMARY KEY (`idBomba`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPag` (
  `idFormaPag` INT NOT NULL,
  `Cartao` VARCHAR(45) NULL,
  `Pix` FLOAT NULL,
  `Dinheiro` FLOAT NULL,
  PRIMARY KEY (`idFormaPag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `idVendas` INT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `FormPag` ENUM('Dinheiro', 'Cartão', 'Pix') NULL,
  `CPF_Empregado` CHAR(11) NULL,
  `BombComb_idBomba` INT NOT NULL,
  `FormaPag_idFormaPag` INT NOT NULL,
  `Empregado_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_Vendas_BombComb1_idx` (`BombComb_idBomba` ASC) VISIBLE,
  INDEX `fk_Vendas_FormaPag1_idx` (`FormaPag_idFormaPag` ASC) VISIBLE,
  INDEX `fk_Vendas_Empregado1_idx` (`Empregado_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_BombComb1`
    FOREIGN KEY (`BombComb_idBomba`)
    REFERENCES `mydb`.`BombComb` (`idBomba`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Vendas_FormaPag1`
    FOREIGN KEY (`FormaPag_idFormaPag`)
    REFERENCES `mydb`.`FormaPag` (`idFormaPag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Empregado1`
    FOREIGN KEY (`Empregado_CPF`)
    REFERENCES `mydb`.`Empregado` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensVenda` (
  `idItem` INT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `IdVenda` INT NOT NULL,
  `Vendas_idVendas` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_ItensVenda_Vendas1_idx` (`Vendas_idVendas` ASC) VISIBLE,
  CONSTRAINT `fk_ItensVenda_Vendas1`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `mydb`.`Vendas` (`idVendas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `Numero` VARCHAR(15) NOT NULL,
  `Empregado_CPF` CHAR(11) NOT NULL,
  `Empregado_CPF1` CHAR(11) NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Empregado1_idx` (`Empregado_CPF1` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Empregado1`
    FOREIGN KEY (`Empregado_CPF1`)
    REFERENCES `mydb`.`Empregado` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Volume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Volume` (
  `idVolume` INT NOT NULL,
  `BombComb_idBomba` INT NOT NULL,
  PRIMARY KEY (`idVolume`),
  INDEX `fk_Volume_BombComb1_idx` (`BombComb_idBomba` ASC) VISIBLE,
  CONSTRAINT `fk_Volume_BombComb1`
    FOREIGN KEY (`BombComb_idBomba`)
    REFERENCES `mydb`.`BombComb` (`idBomba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Combustiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Combustiveis` (
  `idCombustiveis` INT NOT NULL,
  `Combustiveiscol` VARCHAR(45) NOT NULL,
  `BombComb_idBomba` INT NOT NULL,
  PRIMARY KEY (`idCombustiveis`),
  INDEX `fk_Combustiveis_BombComb1_idx` (`BombComb_idBomba` ASC) VISIBLE,
  CONSTRAINT `fk_Combustiveis_BombComb1`
    FOREIGN KEY (`BombComb_idBomba`)
    REFERENCES `mydb`.`BombComb` (`idBomba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
